-- 1. CREATE TABLE  "MEDICINE" 
CREATE TABLE  "MEDICINE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"C_PRICE" FLOAT(80), 
	"S_PRICE" FLOAT(8), 
	"M_MFD" VARCHAR2(11), 
	"M_EXD" VARCHAR2(11), 
	"QTY" NUMBER(8,0), 
	 CONSTRAINT "MEDICINE_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

-- 2. CREATE TABLE  "MEDICINE_DATA" 
CREATE TABLE  "MEDICINE_DATA" 
   (	"ID" NUMBER(5,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"C_PRICE" FLOAT(126), 
	"S_PRICE" FLOAT(126), 
	"M_MFD" VARCHAR2(11), 
	"M_EXD" VARCHAR2(11), 
	"QTY" NUMBER(8,0)
   ) ;
   ALTER TABLE  "MEDICINE_DATA" ADD CONSTRAINT "MEDICINE_DATA_CON" FOREIGN KEY ("ID")
	  REFERENCES  "MEDICINE" ("ID") ON DELETE CASCADE ENABLE;

-- 3. CREATE TABLE  "CUSTOMER" 
CREATE TABLE  "CUSTOMER" 
   (	"C_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"C_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"C_PHNO" NUMBER(13,0) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(7) NOT NULL ENABLE, 
	"T_PRICE" FLOAT(126), 
	"C_DATE" VARCHAR2(11), 
	"T_QTY" NUMBER(5,0), 
	 CONSTRAINT "CUSTOMER_CON" PRIMARY KEY ("C_ID") ENABLE
   ) ;

-- 4. CREATE TABLE  "ORDERS" 
CREATE TABLE  "ORDERS" 
   (	"C_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"O_QTY" NUMBER(10,0) NOT NULL ENABLE, 
	"M_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"T_PRICE" NUMBER(10,0)
   ) ;
    ALTER TABLE  "ORDERS" ADD CONSTRAINT "ORDERS_CON" FOREIGN KEY ("C_ID")
	  REFERENCES  "CUSTOMER" ("C_ID") ON DELETE CASCADE ENABLE;
    ALTER TABLE  "ORDERS" ADD FOREIGN KEY ("M_ID")
	  REFERENCES  "MEDICINE" ("ID") ENABLE;

-- 5. CREATE TABLE  "REPORT_DETAILS" 
    CREATE TABLE  "REPORT_DETAILS" 
   (	"R_ID" NUMBER(5,0), 
	"R_CUSTOMER" NUMBER(5,0), 
	"R_STOCK" NUMBER(12,0), 
	"R_PRODUCT" NUMBER(5,0), 
	"R_COST" NUMBER(12,0), 
	"R_SALES" NUMBER(12,0), 
	"R_DATE" VARCHAR2(12), 
	"R_SALES_CUST" NUMBER(5,0)
   ) ;
